import { z } from "zod";

/** Stable skill IDs probed by the adaptive placement diagnostic. */
export const DIAGNOSTIC_CORE_SKILLS = [
  "python-functions",
  "python-exceptions",
  "data-structures",
  "csv-cleaning",
  "json-validation",
  "financial-data",
  "http-reliability",
  "file-io",
  "llm-output-validation",
] as const;
export type DiagnosticSkillId = (typeof DIAGNOSTIC_CORE_SKILLS)[number];

/** Display metadata for the nine probed skills. Titles are learner-facing. */
export const DIAGNOSTIC_SKILLS: { id: DiagnosticSkillId; title: string }[] = [
  { id: "python-functions", title: "Functions and return contracts" },
  { id: "python-exceptions", title: "Exceptions and error handling" },
  { id: "data-structures", title: "Ordered record transformations" },
  { id: "csv-cleaning", title: "CSV parsing and row validation" },
  { id: "json-validation", title: "JSON envelopes and nested validation" },
  { id: "financial-data", title: "Exact money validation" },
  { id: "http-reliability", title: "HTTP reliability and retries" },
  { id: "file-io", title: "File I/O with context managers" },
  { id: "llm-output-validation", title: "Validating LLM output" },
];

export const diagnosticItemSchema = z.object({
  id: z.string().min(1),
  skillId: z.string().min(1),
  difficulty: z.union([z.literal(1), z.literal(2), z.literal(3)]),
  kind: z.enum(["concept", "coding"]),
  prompt: z.string().min(10),
  hints: z.array(z.string().min(5)).min(2),
  coding: z.object({
    exerciseId: z.string().min(1),
    graderId: z.string().min(1),
    starterCode: z.string().min(1),
    entryFunction: z.string().min(1),
  }).optional(),
  concept: z.object({
    graderId: z.string().min(1),
    gradingNotes: z.string().min(10),
  }).optional(),
}).superRefine((item, ctx) => {
  if (item.kind === "coding" && !item.coding) ctx.addIssue({ code: "custom", message: `coding item ${item.id} needs coding details` });
  if (item.kind === "concept" && !item.concept) ctx.addIssue({ code: "custom", message: `concept item ${item.id} needs concept grading details` });
  if (item.kind === "coding" && item.coding && !item.coding.starterCode.includes(item.coding.entryFunction)) {
    ctx.addIssue({ code: "custom", message: `starter code for ${item.id} must mention ${item.coding.entryFunction}` });
  }
});
export type DiagnosticItem = z.infer<typeof diagnosticItemSchema>;

const concept = (
  id: string, skillId: string, difficulty: 1 | 2 | 3, prompt: string, hints: string[], gradingNotes: string,
): DiagnosticItem => ({ id, skillId, difficulty, kind: "concept", prompt, hints, concept: { graderId: `diagnostic-concept-${id}`, gradingNotes } });
const coding = (
  id: string, skillId: string, difficulty: 1 | 2 | 3, prompt: string, hints: string[],
  exerciseId: string, graderId: string, starterCode: string, entryFunction: string,
): DiagnosticItem => ({ id, skillId, difficulty, kind: "coding", prompt, hints, coding: { exerciseId, graderId, starterCode, entryFunction } });

export const DIAGNOSTIC_ITEMS: DiagnosticItem[] = [
  // ---- python-functions ----
  concept("diag-fn-isqrt-output", "python-functions", 1,
    "What is the exact output of this line? `print(math.isqrt(81))` — type exactly what appears on screen.",
    ["isqrt returns an integer square root, not a string.", "81 = 9 × 9.", "The printed value has no extra words or formatting."],
    "Correct iff the trimmed answer is exactly '9'. Case and surrounding words matter: 'ROOT(81)' and any other text fail."),
  concept("diag-fn-loop-var", "python-functions", 1,
    "In the loop `for x in items:`, what is the name of the loop variable?",
    ["Read the word between `for` and `in`.", "It is a single lowercase letter.", "Type only the variable name."],
    "Correct iff the trimmed answer is exactly 'x'. Any other identifier — including 'YTH', 'y', or 'X' — fails."),
  concept("diag-fn-return", "python-functions", 1,
    "A function ends with `return total`. When the caller writes `result = f()`, does `result` hold printed text or the value of `total`?",
    ["`return` hands a value back; `print` shows text.", "The caller never sees printed output in `result`.", "Answer with what `result` holds."],
    "Correct iff the answer states the caller receives the value of total (accept 'total', 'the value of total', 'returns total'). Answers about printed text fail."),
  concept("diag-fn-default-arg", "python-functions", 2,
    "`def f(items=[]):` — why can this default surprise callers who append to `items`?",
    ["When is a default value created: at definition or at each call?", "Think about what happens on the second call.", "Mutable defaults keep state between calls."],
    "Correct iff the answer conveys the default list is created once and shared across calls (accept 'evaluated once', 'shared', 'same list', 'mutable default persists')."),
  coding("diag-fn-callforms", "python-functions", 2,
    "Write `solve(payload)`: `payload` is a JSON list of numbers like `'[1.2, 2.7]'`. Parse it with `json.loads`, round every number up with `map` and `math.ceil`, and return a plain list.",
    ["Parse first: `json.loads(payload)` gives you the list.", "Round up each value: `map(ceil, values)` then `list(...)`.", "Keyword forms like `json.loads(s=payload)` are fine as long as the call result is used."],
    "diagnostic-call-forms", "diagnostic-call-forms-v1",
    "import json\nfrom math import ceil\n\ndef solve(payload):\n    # payload: a JSON list of numbers, e.g. '[1.2, 2.7]'\n    # Parse it, round each number up, and return a list.\n    return []\n",
    "solve"),

  // ---- python-exceptions ----
  concept("diag-exc-catch", "python-exceptions", 1,
    "`int(text)` raises ValueError on bad input. Should the calling code catch ValueError? Answer yes or no.",
    ["What happens to the program if nobody catches it?", "Catching lets you recover with a message or a default.", "A one-word answer is enough."],
    "Correct iff the answer is affirmative ('yes', 'yes, catch it'). 'no', \"don't catch ValueError\", and 'do not catch' fail — negation must be understood."),
  concept("diag-exc-bare", "python-exceptions", 2,
    "Why is a bare `except:` risky around file-reading code?",
    ["What does a bare `except:` catch?", "Think about KeyboardInterrupt and real bugs.", "Hiding which errors is the danger?"],
    "Correct iff the answer conveys it catches everything — including unexpected bugs, KeyboardInterrupt, and SystemExit — hiding real errors."),
  concept("diag-exc-finally", "python-exceptions", 1,
    "A file is opened, then an error may occur before `close()`. Which block guarantees the file is closed: `except` or `finally`?",
    ["`except` only runs when an error happens.", "One of these blocks always runs.", "Answer with the block name."],
    "Correct iff the answer is 'finally'."),
  concept("diag-exc-raise", "python-exceptions", 2,
    "Validating an age: is it better to `return -1` or `raise ValueError` on bad input? Answer in a few words.",
    ["What does -1 mean to a caller: an error or a valid age?", "Sentinel values can be mistaken for real data.", "Which option makes the failure impossible to ignore?"],
    "Correct iff the answer prefers raising ValueError (accept 'raise', 'raise ValueError'). 'return -1' fails — sentinel values are ambiguous."),
  concept("diag-exc-chain", "python-exceptions", 3,
    "What does `raise ValueError('bad row') from err` preserve that a plain `raise ValueError('bad row')` loses?",
    ["The word `from` links two exceptions.", "What was `err`?", "Debugging is easier when you can see the original failure."],
    "Correct iff the answer mentions chaining the original error — its cause or context (accept 'original exception', 'cause', 'context', 'from err')."),

  // ---- data-structures ----
  concept("diag-ds-clean-value", "data-structures", 2,
    "After `name = '  Ada '` and `clean = (name == 'Ada')`: (1) what is the value of `clean`? (2) write the expression that produces the cleaned name. Answer like: `<value>; <expression>`.",
    ["Compare the raw string to 'Ada' first — are they equal?", "`clean` is True or False; there is no maybe.", "The cleaned name comes from stripping whitespace."],
    "Correct iff the compound answer parses: the first part is False (accept 'False'/'false'), and the second part calls name.strip() (accept 'name.strip()' or 'name = name.strip()'). 'False; name = name.strip()' passes."),
  concept("diag-ds-dict-get", "data-structures", 1,
    "A row dict may lack the 'id' key. Which avoids a KeyError: `row['id']` or `row.get('id')`?",
    ["One of these raises KeyError on a missing key.", "The safe one returns None instead.", "Answer with the safe expression."],
    "Correct iff the answer names `row.get('id')` (accept 'row.get')."),
  concept("diag-ds-comprehension", "data-structures", 2,
    "What does `[s.strip() for s in names]` build: a list, a generator, or None?",
    ["Square brackets build one kind of collection.", "Parentheses would make it lazy.", "Answer with the collection type."],
    "Correct iff the answer is 'list' (accept 'a list')."),
  concept("diag-ds-mutation", "data-structures", 2,
    "`a = [1, 2]` then `b = a` then `b.append(3)`. What is the value of `a` now?",
    ["Does `b = a` copy the list or share it?", "Appending through `b` touches the same object.", "Write the full resulting list."],
    "Correct iff the answer is '[1, 2, 3]' (shared reference). '[1, 2]' fails."),
  concept("diag-ds-sort-key", "data-structures", 3,
    "How do you sort a list of record dicts by their 'amount' field, largest first?",
    ["`sorted` takes a `key` function.", "The key reads the 'amount' field from each record.", "Largest first needs one more argument."],
    "Correct iff the answer mentions sorted()/sort with a key on 'amount' and reverse=True (accept key=lambda r: r['amount'])."),

  // ---- csv-cleaning ----
  concept("diag-csv-header", "csv-cleaning", 1,
    "csv.DictReader turns each row into a dict keyed by what: column position or the header row?",
    ["DictReader reads the first line specially.", "The keys of each row dict come from somewhere.", "Answer: position or header row?"],
    "Correct iff the answer is the header row (accept 'header row', 'headers', 'first row')."),
  concept("diag-csv-strip", "csv-cleaning", 1,
    "A cell reads `' 12.00 '`. What must you do to the text before `Decimal(cell)`?",
    ["Decimal is strict about surrounding characters.", "One string method removes surrounding whitespace.", "Answer with the method name."],
    "Correct iff the answer is strip (accept 'strip', 'strip whitespace', '.strip()')."),
  concept("diag-csv-quoted", "csv-cleaning", 2,
    'How does the csv module read a field written as `"a,b"` — as one field or two?',
    ["The quotes are there for a reason.", "Without them the comma would split the field.", "Answer: one field or two?"],
    "Correct iff the answer is one field (quotes protect the comma)."),
  concept("diag-csv-empty", "csv-cleaning", 2,
    "An amount cell is empty (`''`). In this school's cleaning rules, should the row be kept with amount 0 or rejected?",
    ["Is an empty cell the same as zero?", "Inventing 0 would fabricate money.", "Answer: kept or rejected?"],
    "Correct iff the answer is rejected (missing amounts are invalid; never invent 0)."),

  // ---- json-validation ----
  concept("diag-json-loads", "json-validation", 1,
    "What Python type does `json.loads('[1, 2]')` return?",
    ["The input text describes an array.", "Arrays become one specific Python type.", "Answer with the type name."],
    "Correct iff the answer is 'list'."),
  concept("diag-json-envelope", "json-validation", 2,
    'An API returns `{"payments": [...]}`. Before looping, what must you verify about the payload?',
    ["What if the payload is a list, or null?", "Check the outer shape before touching the inner list.", "Name both checks: the container and the field."],
    "Correct iff the answer conveys validating the envelope: the payload is a dict and 'payments' holds a list."),
  concept("diag-json-decode-error", "json-validation", 1,
    "What exception does `json.loads('{bad')` raise?",
    ["It is an error type from the json module.", "Its name mentions decoding.", "Answer with the exception name."],
    "Correct iff the answer is JSONDecodeError (accept 'json.JSONDecodeError')."),
  concept("diag-json-types", "json-validation", 2,
    "Why check `type(x) is str` rather than just truthiness when validating an id field?",
    ["In Python, `True` is an instance of int.", "Would truthiness accept `True` as an id?", "Strict type checks reject wrong types that look truthy."],
    "Correct iff the answer conveys strict type checking rejects non-strings that truthiness would accept (e.g. True/1)."),
  concept("diag-json-dumps", "json-validation", 2,
    "What does `json.dumps({'a': 1})` return: a dict, a string, or bytes?",
    ["`dumps` serializes to text.", "The result can be written to a file directly.", "Answer with the type."],
    "Correct iff the answer is a string (accept 'string', 'str')."),

  // ---- financial-data ----
  concept("diag-money-decimal", "financial-data", 1,
    "Why is `Decimal('0.10')` safer than `0.1` for money arithmetic?",
    ["How does a computer store 0.1 in binary?", "Try 0.1 + 0.2 in your head — is it exactly 0.3?", "Name the problem with binary floating point."],
    "Correct iff the answer mentions binary floating-point inexactness (accept 'float rounding', '0.1 + 0.2', 'inexact')."),
  concept("diag-money-quantize", "financial-data", 2,
    "How do you force a Decimal amount to exactly two decimal places?",
    ["The Decimal method name starts with 'q'.", "You pass the target precision as Decimal('0.01').", "Answer with the method call."],
    "Correct iff the answer names quantize(Decimal('0.01')) (accept 'quantize')."),
  concept("diag-money-negative", "financial-data", 1,
    "A payment amount of `-5.00` should be accepted, rejected, or converted to `5.00`?",
    ["Can a payment be negative?", "Silently flipping the sign invents money.", "Answer with one of the three options."],
    "Correct iff the answer is rejected."),
  concept("diag-money-currency", "financial-data", 2,
    "How should a currency code like `'usd'` be normalized before comparing to `'USD'`?",
    ["String case must match exactly to compare.", "One method uppercases the whole string.", "Answer with the method name."],
    "Correct iff the answer is upper() (accept 'uppercase', '.upper()')."),

  // ---- http-reliability ----
  concept("diag-http-retry-after", "http-reliability", 1,
    "An API answers 429 with `Retry-After: 30`. Should your client wait before retrying? Answer yes or no.",
    ["429 means you are being rate limited.", "The header tells you how long to wait.", "A one-word answer is enough."],
    "Correct iff the answer is affirmative ('yes', 'yes, wait 30s'). 'no', \"don't wait for Retry-After\", and 'do not wait' fail — negation must be understood."),
  coding("diag-http-success", "http-reliability", 2,
    "Write `is_success(status)`: return True when `status` is an HTTP success code, False otherwise. Remember which family of codes counts as success, and test the edges: 199, 200, 299, 300.",
    ["Success codes are the 2xx family.", "199 is not success; 300 is not success.", "A range check like 200 <= status < 300 handles every edge."],
    "diagnostic-http", "diagnostic-http-v1",
    "def is_success(status):\n    # Return True when status is an HTTP success code, else False.\n    return False\n",
    "is_success"),
  concept("diag-http-2xx", "http-reliability", 1,
    "Which status-code family means HTTP success: 1xx, 2xx, or 3xx?",
    ["1xx is informational.", "3xx means redirection.", "Answer with the family."],
    "Correct iff the answer is '2xx'."),
  concept("diag-http-429", "http-reliability", 2,
    "Your client receives 429 Too Many Requests. Is retrying immediately the right move?",
    ["What does 429 ask you to do?", "Hammering the server makes it worse.", "Name the correct strategy in a few words."],
    "Correct iff the answer is no with waiting/backing off (accept 'no, wait', 'back off', 'no, respect Retry-After'). Bare 'yes' fails."),
  concept("diag-http-timeout", "http-reliability", 2,
    "A request can hang forever. What client setting bounds how long you wait?",
    ["It is a per-request limit in seconds.", "Without it one slow server stalls your program.", "Answer with the setting name."],
    "Correct iff the answer is 'timeout'."),

  // ---- file-io ----
  coding("diag-file-with", "file-io", 2,
    "Write `read_lines(path)`: open the file with a `with`-statement and return its lines with trailing newlines removed. The file object returned by `open()` must be the one the `with`-statement manages.",
    ["`with open(path) as f:` manages the file for you.", "Read the lines inside the block.", "Strip the trailing newline from each line."],
    "diagnostic-files", "diagnostic-files-v1",
    "def read_lines(path):\n    # Open path with a with-statement; return lines without trailing newlines.\n    return []\n",
    "read_lines"),
  concept("diag-file-close", "file-io", 1,
    "What does a `with open(path) as f:` block guarantee about the file, even if an error occurs inside?",
    ["The `with` block has cleanup behavior.", "It runs whether or not the body raises.", "Answer in a few words."],
    "Correct iff the answer conveys the file is closed (accept 'closes the file', 'closed even on error')."),
  concept("diag-file-modes", "file-io", 1,
    "`open(path, 'w')` on an existing file: appends to it, overwrites it, or raises an error?",
    ["'w' stands for one of these behaviors.", "'a' would be the other one.", "Answer with one of the three options."],
    "Correct iff the answer is overwrites (accept 'truncates')."),
  concept("diag-file-readlines", "file-io", 2,
    "What type does `f.readlines()` return?",
    ["It reads every remaining line.", "The result supports indexing and len().", "Answer with the type name."],
    "Correct iff the answer is list (accept 'list of strings', 'list of lines')."),
  concept("diag-file-newline", "file-io", 2,
    "Lines read from a text file end with which character, and how do you remove it?",
    ["The line ending is an escape sequence.", "One string method strips trailing whitespace.", "Name both the character and the method."],
    "Correct iff the answer mentions '\\n' and strip/rstrip."),

  // ---- llm-output-validation ----
  concept("diag-llm-schema", "llm-output-validation", 1,
    "An LLM returns JSON text. What must you do before reading its fields?",
    ["The text might not even be valid JSON.", "Fields might be missing or the wrong type.", "Name the two steps: parse, then …?"],
    "Correct iff the answer conveys parsing and validating against a schema (accept 'parse and validate')."),
  concept("diag-llm-deterministic", "llm-output-validation", 2,
    "Why must you validate an LLM's output shape on every call, not just once?",
    ["Is model output deterministic?", "The same prompt can produce different shapes.", "Name the property that forces repeated validation."],
    "Correct iff the answer conveys nondeterminism — the model may return different shapes on different calls."),
  concept("diag-llm-fallback", "llm-output-validation", 2,
    "The model returns malformed JSON in production. Should the code crash, guess the fields, or use a deterministic fallback?",
    ["Guessing invents data.", "Crashing may be worse than a safe default.", "Answer with one of the three options."],
    "Correct iff the answer chooses the deterministic fallback (accept 'fallback'). Never guess."),
];
