import { curriculum } from "../../lib/curriculum";
import { getDashboardModel, getEvidenceRows, getLibraryRows } from "../../lib/studio";
import type { Studio } from "./use-studio";
import { StageRail } from "./stage-rail";

const formatDate = (value: string) => new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });
function PageHeading({ label, title, children }: { label: string; title: string; children: React.ReactNode }) {
  return <header className="page-heading"><span className="eyebrow">{label}</span><h1 id="page-title" tabIndex={-1}>{title}</h1><p>{children}</p></header>;
}

function Today({ studio }: { studio: Studio }) {
  const model = getDashboardModel(studio.state);
  const reviewOnly = model.selection.kind === "review" || model.run?.mode === "review";
  const available = model.selection.kind !== "complete" && model.mission;
  return <>
    <PageHeading label="TODAY" title="Make room for useful practice.">A small lesson. A working artifact. A clearer understanding of your code.</PageHeading>
    {available && model.mission ? <section className="mission-document" aria-labelledby="mission-title">
      <div className="mission-topline"><span className="eyebrow">{model.run ? "YOUR MISSION IN PROGRESS" : reviewOnly ? "YOUR SCHEDULED REVIEW" : "YOUR NEXT MISSION"}</span><span className="duration">{reviewOnly ? model.mission.stages[0].estimatedMinutes : model.mission.estimatedMinutes} min <span>· suggested pace</span></span></div>
      <div className="mission-intro"><div><h2 id="mission-title">{reviewOnly ? "Bring a familiar pattern back to mind" : model.mission.title}</h2><p>{reviewOnly ? "Revisit the skills scheduled from your saved attempts. A short retrieval will show what needs practice." : model.mission.summary}</p></div><div className="artifact-preview" aria-label="Mission artifact"><span className="file-symbol" aria-hidden="true">.py</span><div><small>YOU’LL BUILD</small><strong>{model.mission.stages[2].tasks[0]?.title}</strong><span>Python · main.py</span></div></div></div>
      <StageRail mission={model.mission} run={model.run} />
      <div className="mission-action"><div><strong>{model.run ? `Pick up at ${model.mission.stages[model.run.stageIndex].title}` : "Begin with a clear plan"}</strong><p>{model.run ? "Your saved code, hints, and place are ready." : model.selection.reviewTaskIds.length ? "Your scheduled retrieval comes first." : "No review is due yet. Start with the mission overview."}</p></div><button className="primary" onClick={() => studio.start()}>{model.run ? "Resume mission" : reviewOnly ? "Start review" : "Start 45-minute mission"}<span aria-hidden="true"> →</span></button></div>
    </section> : <section className="document empty-state"><span className="eyebrow">UP TO DATE</span><h2>You’ve completed the available missions.</h2><p>Your next retrieval appears when a saved skill review is due. Revisit your work in the evidence log.</p><button className="secondary" onClick={() => studio.navigate("learned")}>View your evidence</button></section>}
    <div className="dashboard-columns"><section className="document"><div className="section-heading"><h2>Your learning record</h2><button className="text-button" onClick={() => studio.navigate("learned")}>View log →</button></div>{model.evidence.length ? <ul className="skill-list">{model.evidence.map(skill => <li key={skill.skillId}><span>{skill.title}</span><span className="status-label">{skill.status}</span></li>)}</ul> : <div className="empty-copy"><span className="empty-mark" aria-hidden="true">[ ]</span><h3>Your first evidence starts here.</h3><p>No attempts saved yet. A completed lesson records exposure; independent project checks show what you can do.</p></div>}</section>
      <section className="document"><div className="section-heading"><h2>Coming back to it</h2><span className="eyebrow">REVIEW</span></div>{model.reviews.length ? <ul className="review-list">{model.reviews.map(review => <li key={review.skillId}><strong>{curriculum.skills.find(s => s.id === review.skillId)?.title}</strong><span>{formatDate(review.dueAt)} · {review.reason}</span></li>)}</ul> : <div className="empty-copy"><h3>No reviews scheduled yet.</h3><p>Reviews are scheduled from your actual learning and attempts. They’ll appear here as you work.</p></div>}</section></div>
    <p className="page-footnote">Your work stays in this browser. Reading, practice, and independent evidence are recorded separately.</p>
  </>;
}

function Lessons({ studio }: { studio: Studio }) {
  return <><PageHeading label="LESSON LIBRARY" title="Learn the pattern. Put it to work.">Each mission takes you from a worked example to a project you can explain.</PageHeading><section className="document lesson-library" aria-labelledby="library-title"><div className="library-group"><h2 id="library-title">Reliable data with Python</h2><p>Functions, validation, and useful imports</p></div>{getLibraryRows(studio.state).map((row, index) => <article className="lesson-row" key={row.mission.id}>
      <span className="lesson-index" aria-label={`Mission ${index + 1}`}>{String(index + 1).padStart(2, "0")}</span><div className="lesson-description"><span className="status-label">{row.status}</span><h3>{row.mission.title}</h3><p>{row.mission.summary}</p><span className="artifact-label">Artifact · {row.artifact}</span>{row.blockedReason && <p className="prerequisite">{row.blockedReason}</p>}</div><div className="lesson-action"><span className="duration">{row.mission.estimatedMinutes} min</span><button className="secondary" disabled={Boolean(row.blockedReason)} onClick={() => studio.start(row.mission.id)}>{row.status === "In progress" ? "Resume mission" : row.status === "Completed" ? "Practice again" : "Open mission"}<span aria-hidden="true"> →</span></button></div>
    </article>)}</section><p className="page-footnote">The library shows the authored missions available today. Progress reflects saved mission runs.</p></>;
}

function Learned({ studio }: { studio: Studio }) {
  const rows = getEvidenceRows(studio.state);
  return <><PageHeading label="EVIDENCE LOG" title="Your work, with the receipts.">Saved attempts show what you tried, what passed, and how much help you used.</PageHeading>{rows.length ? <section className="evidence-list" aria-label="Saved attempts">{rows.map(row => {
    const code = row.attempt.purpose !== "instruction" && row.attempt.purpose !== "reflection";
    const label = row.attempt.purpose === "instruction" ? "Lesson read" : row.attempt.purpose === "reflection" ? "Reflection saved" : row.attempt.passed ? "Passed" : row.attempt.executionOk ? "Needs changes" : "Couldn't run";
    return <details className="document evidence-entry" key={row.attempt.id}><summary><div className="evidence-date"><time dateTime={row.attempt.completedAt}>{formatDate(row.attempt.completedAt)}</time><span>{new Date(row.attempt.completedAt).toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" })}</span></div><div className="evidence-description"><h2>{row.title}</h2><p>{row.attempt.purpose.replaceAll("-", " ")} · {row.assistance}</p><span>{code ? `${row.attempt.checks.filter(c => c.passed).length}/${row.attempt.checks.length} checks passed` : "Not a graded skill claim"}{row.nextReview ? ` · Next review ${formatDate(row.nextReview)}` : " · No review scheduled"}</span></div><span className={`result-label ${code ? row.attempt.passed ? "success" : "failure" : ""}`}>{label}</span><span className="details-chevron" aria-hidden="true">⌄</span></summary><div className="evidence-details"><p className="muted">{row.missionTitle}{row.attempt.duplicateOf ? " · Repeated submission; no additional mastery credit." : ""}</p>{Object.entries(row.attempt.sourceFiles).map(([file, source]) => <div key={file}><h3>{file}</h3><pre>{source}</pre></div>)}{row.attempt.response && <div><h3>Your reflection</h3><p>{row.attempt.response}</p></div>}{row.attempt.checks.length > 0 && <ul className="saved-checks">{row.attempt.checks.map(check => <li key={check.id}><strong>{check.passed ? "Passed" : "Needs changes"}: {check.name}</strong>{check.detail && <p>{check.detail}</p>}</li>)}</ul>}<p className="muted">{row.assistance}. {row.attempt.purpose === "guided-practice" ? "Guided practice does not establish independent project evidence." : row.attempt.purpose === "project" && row.attempt.passed ? "Mastery requires varied independent evidence and later retrieval." : "This is a record of this attempt only."}</p></div></details>;
  })}</section> : <section className="document large-empty"><span className="empty-mark" aria-hidden="true">[ ]</span><h2>No saved attempts yet.</h2><p>Start a mission to create your first learning record. Your code, check results, hints, and reflections will appear here.</p><button className="primary" onClick={() => studio.start()}>Start your first mission →</button></section>}</>;
}

function Assessment({ studio }: { studio: Studio }) {
  const model = getDashboardModel(studio.state);
  const projects = studio.state.attempts.filter(a => a.purpose === "project");
  return <><PageHeading label="SELF-ASSESSMENT" title="See where your code stands.">Use a real project to establish a baseline you can return to.</PageHeading><section className="document assessment-document"><span className="eyebrow">PROJECT-BASED BASELINE</span><h2>{projects.length ? "You have project attempts to reflect on." : "Your baseline hasn’t been established yet."}</h2><p>{projects.length ? `Your log contains ${projects.length} saved project attempt${projects.length === 1 ? "" : "s"}. Review the checks and assistance before deciding what to practise next.` : "Work through a short lesson and guided practice, then build the payments importer. The checks give you a concrete starting point."}</p><ol className="assessment-steps"><li><strong>Refresh the building blocks</strong><span>Read the pattern, then practise on a small input.</span></li><li><strong>Build a working artifact</strong><span>Run the required checks and keep the result.</span></li><li><strong>Explain your decisions</strong><span>Record what you understand and what still needs work.</span></li></ol><p className="assessment-note">Adaptive assessment is not available yet. This baseline uses saved project checks and your reflection; it does not generate an adaptive score.</p><div className="button-row">{model.selection.kind !== "complete" && <button className="primary" onClick={() => studio.start()}>{model.run ? "Resume baseline mission" : "Start baseline mission"} →</button>}{projects.length > 0 && <button className="secondary" onClick={() => studio.navigate("learned")}>Review project attempts</button>}</div></section></>;
}

export function Dashboard({ studio }: { studio: Studio }) {
  return <main id="main-content" className="dashboard">{studio.route.destination === "lessons" ? <Lessons studio={studio} /> : studio.route.destination === "learned" ? <Learned studio={studio} /> : studio.route.destination === "assessment" ? <Assessment studio={studio} /> : <Today studio={studio} />}</main>;
}
