import { useState } from "react";
import Editor, { loader } from "@monaco-editor/react";
import { currentDiagnostic, deriveDiagnosticProfile, diagnosticSkills, getDiagnosticItem, placementRecommendation } from "../../lib/diagnostic";
import { getDashboardModel } from "../../lib/studio";
import type { Studio } from "./use-studio";
loader.config({ paths: { vs: "/monaco/vs" } });

export function BaselineEntry({studio,compact=false}:{studio:Studio;compact?:boolean}){
  const session=currentDiagnostic(studio.state);
  return <section className={compact?"document baseline-entry":"mission-document baseline-entry"} aria-labelledby="baseline-title">
    <div className="mission-topline"><span className="eyebrow">PLACEMENT BASELINE</span><span className="duration">12–25 questions · save & resume</span></div>
    <h2 id="baseline-title">{session?.status==="completed"?"Your observed starting point":session?"Continue your placement baseline":"Establish your placement baseline"}</h2>
    <p>Read small pieces of Python, debug an example, and write working code. Your answers shape a practical starting recommendation.</p>
    <div className="baseline-stages"><span>01 · Probe the foundations</span><span>02 · Try adaptive follow-ups</span><span>03 · Choose your first mission</span></div>
    <div className="mission-action"><p>{session?.status==="active"?`${session.responses.length} answers saved. Your current question and code are ready.`:"This is initial placement. Project reviews and later retrieval establish learning over time."}</p><button className="primary" onClick={()=>studio.beginBaseline()}>{session?.status==="completed"?"View placement profile":session?"Resume placement baseline":"Start placement baseline"} →</button></div>
  </section>;
}
export function BaselineProfile({studio}:{studio:Studio}){
  const session=currentDiagnostic(studio.state);if(!session)return <BaselineEntry studio={studio}/>;
  const profile=deriveDiagnosticProfile(session);const model=getDashboardModel(studio.state);
  const recommendation=placementRecommendation(studio.state,model.mission?.id??"");
  const strengths=profile.filter(p=>p.band==="Strong evidence");
  return <><header className="page-heading"><span className="eyebrow">PLACEMENT RESULTS</span><h1 id="page-title" tabIndex={-1}>Your observed starting point.</h1><p>{session.responses.length} questions saved. This is a sample of current performance; it does not complete lessons or establish mastery.</p></header>
    <section className="document"><h2>Observed strengths</h2><p>{strengths.length?strengths.map(p=>diagnosticSkills.find(s=>s.id===p.skillId)!.title).join(" · "):"No varied independent practical strength is established yet. The observations below show where to begin."}</p><h2>Recommended first mission</h2><h3>{model.mission?.title??"Resume your learning record"}</h3><p>{model.selection.kind==="resume"?"Your active mission comes first. The baseline does not move your saved place.":recommendation.reason}</p><div className="button-row"><button className="primary" onClick={()=>studio.navigate("today")}>See recommendation on Today →</button><button className="secondary" onClick={()=>studio.start()}> {model.run?"Resume mission":"Start recommended mission"}</button></div></section>
    <section className="document"><h2>Skill evidence and prerequisites</h2><p>Working evidence is limited or assisted. Needs practice includes conflicting results. Untested means no observed answer, including questions skipped. Expand a skill to inspect every source response.</p>
      <div className="baseline-skill-grid">{profile.map(p=>{const skill=diagnosticSkills.find(s=>s.id===p.skillId)!;return <details className="baseline-skill" key={p.skillId}><summary><strong>{skill.title}</strong><span className={`status-label band-${p.band.replaceAll(" ","-").toLowerCase()}`}>{p.band}</span><span>{p.evidenceCount} observations · {p.confidence} confidence</span></summary><p>Prerequisites: {skill.prerequisites.length?skill.prerequisites.map(id=>diagnosticSkills.find(s=>s.id===id)!.title).join(", "):"None"}.</p><p>{p.notes}</p><p>Latest result: {p.latestResult?.replaceAll("-"," ")??"Not tested"}.</p>{p.responseIds.map(id=>{const response=session.responses.find(r=>r.id===id)!;const attempt=session.attempts.find(a=>a.id===response.attemptId);return <article className="baseline-source" key={id}><h4>{getDiagnosticItem(response.itemId)?.title}</h4><p>{response.feedback}</p><p>Response ID: <code>{id}</code></p>{attempt&&<><p>Attempt ID: <code>{attempt.id}</code></p><pre>{attempt.sourceFiles["main.py"]}</pre><ul>{attempt.checks.map(c=><li key={c.id}>{c.passed?"Passed":"Needs practice"}: {c.name}</li>)}</ul></>}{response.answer&&<pre>{response.answer}</pre>}{session.attempts.filter(a=>a.itemId===response.itemId&&a.id!==response.attemptId).map(a=><details key={a.id}><summary>Earlier coding trial · {a.passed?"Passed":"Needs practice"}</summary><p>Attempt ID: <code>{a.id}</code></p><pre>{a.sourceFiles["main.py"]}</pre><ul>{a.checks.map(c=><li key={c.id}>{c.passed?"Passed":"Needs practice"}: {c.name}</li>)}</ul></details>)}<p>{response.hintsUsed?"Hint used":"No hint"} · {response.aiAssisted?"External assistance":"No external assistance recorded"}</p></article>;})}</details>;})}</div>
    </section><section className="document"><h2>Revisit after practice</h2><p>You can retake this baseline after learning. A retake creates a separate session and preserves this evidence. An unfinished retake resumes at its current question. It cannot overwrite mission completion or mastery.</p><button className="secondary" onClick={()=>studio.beginBaseline(true)}>Start a new placement baseline</button></section></>;
}
export function DiagnosticWorkbench({studio}:{studio:Studio}){
  const [plain,setPlain]=useState(false);
  const {baseline:session,baselineItem:item,baselineDraft:draft}=studio;
  if(!session)return <main id="main-content" className="dashboard"><BaselineEntry studio={studio}/></main>;
  if(session.status==="completed")return <main id="main-content" className="dashboard baseline-results"><BaselineProfile studio={studio}/></main>;
  if(!item||!draft)return null;
  const latest=session.attempts.filter(a=>a.itemId===item.id&&a.sourceFiles["main.py"]===draft.sourceFiles["main.py"]).at(-1);
  return <main id="main-content" className="dashboard baseline-workbench"><header className="page-heading"><button className="text-button" onClick={()=>studio.navigate("today")}>← Save & return to Today</button><span className="eyebrow">PLACEMENT BASELINE · {item.kind==="code"?"WRITE PYTHON":"READ & REASON"}</span><h1 id="page-title" tabIndex={-1}>{item.title}</h1><p role="status">Question {session.responses.length+1}, at least 12; up to 25</p><p>{diagnosticSkills.find(s=>s.id===item.skillId)?.title} · {item.difficulty===1?"Foundation check":item.difficulty===3?"Follow-up challenge":"Breadth probe"}</p></header>
    <section className="document"><h2>Your task</h2><pre className="baseline-prompt">{item.prompt}</pre><p>{item.expectedBehavior}</p>
      {item.kind==="short"?<div className="reflection-input"><label htmlFor="baseline-answer">Your answer</label><textarea id="baseline-answer" rows={5} value={draft.answer} onChange={e=>studio.updateBaselineDraft({answer:e.target.value})}/><p>Use a concise answer in the requested format. The rubric accepts stated semantic equivalents; an unrecognized answer remains an uncertainty.</p></div>:<section aria-label="Python coding workspace" className="baseline-editor"><div className="section-heading"><label htmlFor="baseline-code">Python code · main.py</label><button className="text-button" onClick={()=>setPlain(!plain)}>{plain?"Use code editor":"Use plain text"}</button></div>{plain?<textarea id="baseline-code" aria-label="Python code" rows={13} spellCheck={false} value={draft.sourceFiles["main.py"]} onChange={e=>studio.updateBaselineDraft({sourceFiles:{"main.py":e.target.value}})}/>:<Editor height="300px" language="python" value={draft.sourceFiles["main.py"]} onChange={value=>studio.updateBaselineDraft({sourceFiles:{"main.py":value??""}})} options={{minimap:{enabled:false},fontSize:14,wordWrap:"on",scrollBeyondLastLine:false,automaticLayout:true,accessibilitySupport:"on",ariaLabel:"Python code"}}/>}<div className="button-row"><button className="primary" disabled={studio.busy} onClick={studio.runBaselineChecks}>Run checks</button>{studio.busy&&<button className="secondary" onClick={studio.stopRun}>Stop Python</button>}<span className="run-status" role="status">{studio.status==="Ready"&&latest?latest.passed?"Passed · saved":"Needs changes · saved":studio.status}</span></div>{(studio.result||latest)&&<div className="baseline-checks"><p>{latest?"Attempt saved. You may revise the code or record this result and continue.":"Saving the check result…"}</p><ul>{(studio.result?.tests??latest?.checks??[]).map(c=><li key={c.id}><strong>{c.passed?"Passed":"Needs changes"}: {c.name}</strong>{c.detail&&<p>{c.detail}</p>}</li>)}</ul>{studio.result?.stderr&&<pre>{studio.result.stderr}</pre>}</div>}</section>}
      <details className="baseline-help"><summary>Record assistance or use a hint</summary><p>Help stays attached to this answer. Baseline solutions are unavailable.</p>{draft.hintsUsed?<p className="hint">{item.hint}</p>:<button className="secondary" onClick={()=>studio.updateBaselineDraft({hintsUsed:1})}>Reveal hint</button>}<label><input type="checkbox" checked={draft.aiAssisted} disabled={draft.aiAssisted} onChange={()=>studio.updateBaselineDraft({aiAssisted:true})}/> I used external help, including AI</label></details>
      <div className="button-row baseline-submit"><button className="primary" disabled={studio.busy||studio.saving||(item.kind==="code"?!latest:!draft.answer.trim())} onClick={()=>studio.answerBaseline()}>{item.kind==="code"?"Record attempt & continue":"Save answer & continue"} →</button>{item.kind==="short"&&<button className="secondary" disabled={studio.busy||studio.saving} onClick={()=>studio.answerBaseline(true)}>I don’t know yet</button>}</div>
    </section><p className="page-footnote">Your exact question, draft, hints and attempts are saved to SQLite. Wait for “Stored on this computer” before closing this tab.</p></main>;
}
