"use client";
import Editor from "@monaco-editor/react";
import { useEffect, useRef, useState } from "react";
import { curriculum, type Lesson } from "../lib/curriculum";
import { startGradingRun, type GradeResult } from "../lib/runner";
import { getGrader } from "../public/grading/catalog.js";
export default function Home() {
  const [view, setView] = useState<"diagnostic"|"dashboard"|"lab">("dashboard"); const [q, setQ] = useState(1); const [tab,setTab]=useState<"today"|"lessons"|"learned"|"assessment">("today"); const [lesson,setLesson]=useState<Lesson>(curriculum.lessons[0]); const [code,setCode]=useState(lesson.exercise.starterFiles["main.py"]); const [hints,setHints]=useState(0); const [result,setResult]=useState<GradeResult|null>(null); const [running,setRunning]=useState(false); const cancelRun=useRef<(()=>void)|null>(null);
  useEffect(()=>()=>cancelRun.current?.(),[]);
  const cancel=()=>{cancelRun.current?.();cancelRun.current=null;setRunning(false)};
  const open=(item:Lesson)=>{cancel();setLesson(item);setCode(item.exercise.starterFiles["main.py"]);setResult(null);setHints(0);setView("lab")};
  const edit=(value:string)=>{cancel();setCode(value);setResult(null)};
  const run=()=>{cancel();setResult(null);setRunning(true);cancelRun.current=startGradingRun({type:"run",requestId:crypto.randomUUID(),exerciseId:lesson.exercise.id,graderId:lesson.exercise.graderId,files:{"main.py":code}},data=>{setRunning(false);setResult(data)})};
  if(view==="diagnostic") return <main className="onboarding"><span className="eyebrow">WORKBENCH SCHOOL / INITIAL SIGNAL</span><h1>Show what still<br/>works under pressure.</h1><p>This diagnostic adapts. Confident, varied evidence lets us move on; uncertain evidence earns a better next question.</p><section><span>Question {q} · minimum 12 / maximum 25</span><h2>{["What does a function return without return?","Write a loop that totals valid amounts.","How should missing JSON fields be handled?","Read this traceback: what failed first?"][q%4]}</h2><button onClick={()=>setQ(q+1)}>I can explain it</button><button className="quiet" onClick={()=>setQ(q+1)}>I need a refresher</button>{q>=4&&<button className="primary" onClick={()=>setView("dashboard")}>Generate skill profile →</button>}</section></main>;
  if(view==="dashboard") return <main className="shell"><aside><b className="mark">WB•01</b><nav><button onClick={()=>setTab("today")}>Today</button><button onClick={()=>setTab("lessons")}>Lessons</button><button onClick={()=>setTab("learned")}>What I learned</button><button onClick={()=>setTab("assessment")}>Self-assessment</button></nav><p><span className="eyebrow">LEARNING MODE</span><br/>Completion is logged. Mastery is earned separately.</p></aside><section className="dashboard">{tab==="today"?<><span className="eyebrow">TODAY / DAY 01</span><h1>Repair a payments export.</h1><div className="mission"><div><span className="eyebrow">TODAY’S MISSION</span><h2>Make unreliable data safe to use.</h2><p>Parse malformed records, expose bad values, and return clean rows a teammate can trust.</p><button className="primary" onClick={()=>open(curriculum.lessons[0])}>Open workbench →</button></div><b>45 <small>focused minutes</small></b></div><div className="grid"><section><span className="eyebrow">SKILL SIGNALS</span>{curriculum.skills.slice(0,5).map((s,i)=><p className="skill" key={s.id}>{s.title}<i><b style={{width:`${[78,64,71,35,28][i]}%`}}/></i><em>{[78,64,71,35,28][i]}%</em></p>)}</section><section><span className="eyebrow">DUE FOR RETRIEVAL</span><h3>Functions & scope</h3><p>One independent challenge due today.</p><button className="quiet" onClick={()=>open(curriculum.lessons[1])}>Practice now</button></section></div></>:tab==="lessons"?<><span className="eyebrow">CURRICULUM</span><h1>Choose the next useful problem.</h1><div className="grid">{curriculum.lessons.map(item=><section key={item.id}><span className="eyebrow">{item.estimatedMinutes} MIN · {item.skillId}</span><h3>{item.title}</h3><p>{item.dailyProject}</p><button className="quiet" onClick={()=>open(item)}>Open lesson</button></section>)}</div></>:tab==="learned"?<><span className="eyebrow">EVIDENCE LOG</span><h1>What you’ve actually demonstrated.</h1><div className="grid"><section><h3>Recently learned</h3><p>Data structures · CSV parsing · Debugging stack traces</p></section><section><h3>Due next</h3><p>Independent functions retrieval practice</p></section></div></>:<><span className="eyebrow">SELF-ASSESSMENT</span><h1>Calibrate your next week.</h1><p>Retake a compact adaptive assessment whenever your confidence and evidence disagree.</p><button className="primary" onClick={()=>setView("diagnostic")}>Start self-assessment →</button></>}</section></main>;
  return <main className="lab"><header><button onClick={()=>{cancel();setView("dashboard")}}>← Mission control</button><span>{lesson.title.toUpperCase()}</span><label><input type="checkbox" defaultChecked/> Learning Mode</label></header><div className="panes"><aside><span className="eyebrow">OBJECTIVE</span><h1>{lesson.title}</h1><p>{lesson.explanation}</p><h3>Success checks</h3>{lesson.exercise.visibleRequirements.map(x=><p key={x}>□ {x}</p>)}<h3>Example input / expected output</h3>{lesson.examples.map(x=><pre key={x}>{x}</pre>)}<h3>Hints</h3>{lesson.exercise.hints.slice(0,hints).map((x,i)=><p className="hint" key={x}>{i+1}. {x}</p>)}{hints<4&&<button className="quiet" onClick={()=>setHints(hints+1)}>Reveal hint {hints+1}</button>}<hr/><span className="eyebrow">DAILY PROJECT</span><b>{lesson.dailyProject}</b></aside><section className="editor"><div>main.py <small>Python / isolated worker</small></div><Editor theme="vs-dark" language="python" value={code} onChange={v=>edit(v??"")} options={{minimap:{enabled:false},fontSize:14}}/><footer><button className="primary" disabled={running||!getGrader(lesson.exercise.id,lesson.exercise.graderId)} onClick={run}>{running?"Running…":getGrader(lesson.exercise.id,lesson.exercise.graderId)?"Run checks":"Grader unavailable"}</button><button className="quiet" onClick={()=>edit(lesson.exercise.starterFiles["main.py"])}>Reset</button></footer></section><aside><span className="eyebrow">AUTOGRADER</span><h2>{result?(result.passed?"Evidence captured":"Needs another pass"):"Run your work"}</h2>{result?<><pre>{result.stdout||"No standard output."}{result.stderr?`\n${result.stderr}`:""}</pre>{result.tests.map(t=><p className={t.passed?"pass":"fail"} key={t.id}>{t.passed?"✓":"×"} {t.name}{t.detail&&<small> — {t.detail}</small>}</p>)}<p className="muted">Completion and mastery are separate. {hints?`${hints} hint(s) reduce evidence weight.`:"Independent work receives full evidence weight."}</p></>:<p className="muted">Checks evaluate exact return values and required Python concepts. Evidence is captured only when every required check passes.</p>}</aside></div></main>;
}
